# Generates one-click install links + per-client mcp.json snippets from the ONE
# canonical config (install/config.json) so README buttons, deeplinks, and snippets
# can never drift from each other.
#
#   pwsh install/generate-install-links.ps1          # regenerate install/generated/ + README block
#   pwsh install/generate-install-links.ps1 -Check   # exit 1 if anything is out of date (CI drift guard)
#
# The package version is read from build/dependencies.props at generation time -
# config.json intentionally has no version field. Compatible with Windows
# PowerShell 5.1 and pwsh 7+; output is UTF-8 (no BOM) with LF endings so the
# same bytes are produced on every OS (see .gitattributes).
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$genDir   = Join-Path $PSScriptRoot 'generated'

# ---------------------------------------------------------------- inputs
$cfg = Get-Content (Join-Path $PSScriptRoot 'config.json') -Raw | ConvertFrom-Json

$propName  = ($cfg.packageId -replace '\.', '')   # GroupDocs.Conversion.Mcp -> GroupDocsConversionMcp
$depsText  = Get-Content (Join-Path $repoRoot 'build/dependencies.props') -Raw
$m = [regex]::Match($depsText, "<$propName>([^<]+)</$propName>")
if (-not $m.Success) { throw "Version property <$propName> not found in build/dependencies.props" }
$version = $m.Groups[1].Value.Trim()

$name      = $cfg.name
$pkg       = $cfg.packageId
$argsJson  = '["' + ($cfg.args -join '", "') + '"]'

# ---------------------------------------------------------------- JSON fragments
# Built as literal strings (NOT ConvertTo-Json) so output is byte-identical across
# PowerShell versions - required for the CI drift guard.
$envBlock = @"
        "GROUPDOCS_MCP_STORAGE_PATH": "/path/to/documents",
        "GROUPDOCS_LICENSE_PATH": "/path/to/GroupDocs.Total.lic"
"@

$mcpServersSnippet = @"
{
  "mcpServers": {
    "$name": {
      "type": "stdio",
      "command": "$($cfg.command)",
      "args": $argsJson,
      "env": {
$envBlock
      }
    }
  }
}
"@

$vscodeSnippet = @"
{
  "inputs": [
    {
      "type": "promptString",
      "id": "storage_path",
      "description": "Base folder for input and output files.",
      "password": false
    },
    {
      "type": "promptString",
      "id": "license_path",
      "description": "Path to GroupDocs license file (optional - evaluation mode if empty).",
      "password": false
    }
  ],
  "servers": {
    "$name": {
      "type": "stdio",
      "command": "$($cfg.command)",
      "args": $argsJson,
      "env": {
        "GROUPDOCS_MCP_STORAGE_PATH": "`${input:storage_path}",
        "GROUPDOCS_LICENSE_PATH": "`${input:license_path}"
      }
    }
  }
}
"@

# ---------------------------------------------------------------- one-click URLs
# EscapeDataString diverges between .NET Framework (PS 5.1, RFC 2396: leaves !'()*
# unescaped) and modern .NET (pwsh, RFC 3986: escapes them). Normalize so the
# generated bytes are identical on both - required for the CI drift guard.
function Escape-Uri([string]$s) {
    $e = [uri]::EscapeDataString($s)
    $e.Replace('(', '%28').Replace(')', '%29').Replace('!', '%21').Replace("'", '%27').Replace('*', '%2A')
}

# vscode.dev's WAF (Azure Front Door) blocks any request carrying an `inputs=` query
# parameter (403 'The request is blocked'), so the one-click deeplink config is
# prompt-less: command+args only. The note under the buttons tells users how to set
# their storage folder after install. Verified empirically 2026-07-25 (inputs= -> 403,
# config-only -> 302 to vscode:mcp/install on both vscode.dev and insiders.vscode.dev).
$vscodeConfig = '{"command":"' + $cfg.command + '","args":' + ($argsJson -replace '", "', '","') + '}'
$encName   = Escape-Uri $name
$encConfig = Escape-Uri $vscodeConfig
$vscodeUrl         = "https://vscode.dev/redirect/mcp/install?name=$encName&config=$encConfig"
$vscodeInsidersUrl = "https://insiders.vscode.dev/redirect/mcp/install?name=$encName&config=$encConfig&quality=insiders"

# Cursor: TODO(verify) - format per cursor.com deeplink docs (name + base64 config);
# re-check against current Cursor docs before each rollout wave, it has changed before.
$cursorConfig = '{"command":"' + $cfg.command + '","args":' + ($argsJson -replace '", "', '","') + ',"env":{"GROUPDOCS_MCP_STORAGE_PATH":"/path/to/documents"}}'
$cursorB64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($cursorConfig))
$cursorUrl = "https://cursor.com/en/install-mcp?name=$encName&config=$(Escape-Uri $cursorB64)"

$badgeVsCode   = "[![Install in VS Code](https://img.shields.io/badge/VS_Code-Install-0098FF)](${vscodeUrl})"
$badgeInsiders = "[![Install in VS Code Insiders](https://img.shields.io/badge/VS_Code_Insiders-Install-24bfa5)](${vscodeInsidersUrl})"
$badgeCursor   = "[![Add to Cursor](https://img.shields.io/badge/Cursor-Add_MCP-111111)](${cursorUrl})"

$pinNoteCodex = "Pin a version by replacing ``$pkg`` with ``$pkg@$version``."

# ---------------------------------------------------------------- generated files
$files = [ordered]@{}

$files['claude-desktop.json'] = $mcpServersSnippet
$files['windsurf.json']       = $mcpServersSnippet
$files['cline.json']          = $mcpServersSnippet
$files['vscode-mcp.json']     = $vscodeSnippet
$files['vs2022-mcp.json']     = $vscodeSnippet   # VS 2022 17.14+ reads the same shape from .mcp.json in the solution root

$files['claude-code.md'] = @"
# Claude Code

``````bash
claude mcp add $name -- $($cfg.command) $($cfg.args -join ' ')
``````

With storage folder and license:

``````bash
claude mcp add $name -e GROUPDOCS_MCP_STORAGE_PATH=/path/to/documents -e GROUPDOCS_LICENSE_PATH=/path/to/GroupDocs.Total.lic -- $($cfg.command) $($cfg.args -join ' ')
``````

Pin a version by replacing ``$pkg`` with ``$pkg@$version``.
"@

$files['rider.md'] = @"
# JetBrains Rider (2025.2+)

Settings -> Tools -> AI Assistant -> Model Context Protocol (MCP) -> Add. Choose
**As JSON** and paste:

``````json
{
  "name": "$name",
  "command": "$($cfg.command)",
  "args": $argsJson,
  "env": {
    "GROUPDOCS_MCP_STORAGE_PATH": "/path/to/documents",
    "GROUPDOCS_LICENSE_PATH": "/path/to/GroupDocs.Total.lic"
  }
}
``````

Remove ``GROUPDOCS_LICENSE_PATH`` to run in evaluation mode. Pin a version by
replacing ``$pkg`` with ``$pkg@$version``.
"@

$files['codex.md'] = @"
# Codex CLI (OpenAI)

``````bash
codex mcp add $name -- $($cfg.command) $($cfg.args -join ' ')
``````

Or add to ``~/.codex/config.toml``:

``````toml
[mcp_servers.$name]
command = "$($cfg.command)"
args = $argsJson

[mcp_servers.$name.env]
GROUPDOCS_MCP_STORAGE_PATH = "/path/to/documents"
# GROUPDOCS_LICENSE_PATH = "/path/to/GroupDocs.Total.lic"   # omit for evaluation mode
``````

$pinNoteCodex
"@

$files['windsurf.md'] = @"
# Windsurf

Windsurf has no MCP CLI - add the server via its config file:

1. Open Windsurf -> Settings -> Cascade -> Manage MCP servers -> View raw config
   (or edit ``~/.codeium/windsurf/mcp_config.json`` directly).
2. Merge in the contents of ``windsurf.json`` from this folder.
3. Refresh the MCP server list.

Remove ``GROUPDOCS_LICENSE_PATH`` from the pasted config to run in evaluation mode.
$pinNoteCodex
"@

$files['install-links.md'] = @"
# Generated install links - $($cfg.displayName) MCP (source: install/config.json, version $version)

Do not edit by hand; run ``pwsh install/generate-install-links.ps1``.

## One-click

- VS Code: $vscodeUrl
- VS Code Insiders: $vscodeInsidersUrl
- Cursor (TODO(verify): re-check deeplink format against current Cursor docs before relying on it): $cursorUrl

## Badges

$badgeVsCode
$badgeInsiders
$badgeCursor
"@

$readmeBlock = @"
<!-- install-buttons:start - generated by install/generate-install-links.ps1; do not edit by hand -->
$badgeVsCode $badgeInsiders $badgeCursor

> One-click installs write a minimal config (storage defaults to the client's working
> directory). To use a specific documents folder or a license, add the
> GROUPDOCS_MCP_STORAGE_PATH / GROUPDOCS_LICENSE_PATH env vars to the written entry.
>
> **More clients** - ready-made configs for Claude Code, Codex CLI, Visual Studio 2022,
> Cursor, Windsurf, Cline, and JetBrains Rider live in [``install/generated/``](install/generated/).
<!-- install-buttons:end -->
"@

# ---------------------------------------------------------------- write / check
function Write-Lf([string]$Path, [string]$Content) {
    $lf = ($Content -replace "`r`n", "`n")
    if (-not $lf.EndsWith("`n")) { $lf += "`n" }
    [System.IO.File]::WriteAllText($Path, $lf, (New-Object System.Text.UTF8Encoding($false)))
}
function Read-Norm([string]$Path) {
    if (-not (Test-Path $Path)) { return $null }
    ([System.IO.File]::ReadAllText($Path) -replace "`r`n", "`n")
}

$drift = @()
if (-not (Test-Path $genDir)) { New-Item -ItemType Directory -Path $genDir | Out-Null }

foreach ($fname in $files.Keys) {
    $path = Join-Path $genDir $fname
    $new  = (($files[$fname]) -replace "`r`n", "`n")
    if (-not $new.EndsWith("`n")) { $new += "`n" }
    if ((Read-Norm $path) -ne $new) {
        $drift += "install/generated/$fname"
        if (-not $Check) { Write-Lf $path $files[$fname] }
    }
}

# README block injection (only the marker region is touched)
$readmePath = Join-Path $repoRoot 'README.md'
$readme = [System.IO.File]::ReadAllText($readmePath)
$pattern = '(?s)<!-- install-buttons:start.*?install-buttons:end -->'
if ($readme -notmatch $pattern) { throw "README.md is missing the <!-- install-buttons:start/end --> marker block" }
$newReadme = [regex]::Replace($readme, $pattern, ($readmeBlock -replace "`r`n", "`n"))
if ($newReadme -ne $readme) {
    $drift += 'README.md (install-buttons block)'
    if (-not $Check) { [System.IO.File]::WriteAllText($readmePath, $newReadme, (New-Object System.Text.UTF8Encoding($false))) }
}

if ($Check) {
    if ($drift.Count -gt 0) {
        Write-Host "DRIFT - regenerate with: pwsh install/generate-install-links.ps1"
        $drift | ForEach-Object { Write-Host "  out of date: $_" }
        exit 1
    }
    Write-Host "install/generated + README install block are up to date (version $version)."
} else {
    Write-Host "Generated $($files.Keys.Count) files (version $version); README block updated."
    if ($drift.Count -eq 0) { Write-Host "  (no changes - already up to date)" }
}
